version: '3.8'

services:
  backup:
    image: postgres:15-alpine
    volumes:
      - ./backups:/backups
    environment:
      - PGPASSWORD=${POSTGRES_PASSWORD:-postgres}
    command: >
      sh -c "mkdir -p /backups && 
             pg_dump -h postgres -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-localspot} -F c -f /backups/localspot_$(date +%Y%m%d_%H%M%S).dump && 
             echo 'Backup completed successfully! File saved to ./backups/'"
    networks:
      - default
    depends_on:
      - postgres

networks:
  default:
    external:
      name: localspot_default