version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=localspot
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backup:
    image: postgres:15-alpine
    volumes:
      - ./backups:/backups
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    depends_on:
      - postgres
    entrypoint: |
      bash -c '
        mkdir -p /backups
        echo "Backing up PostgreSQL database..."
        pg_dump -h postgres -U postgres -d localspot > /backups/backup_$(date +%Y%m%d_%H%M%S).sql
        echo "Backup completed"
        echo "Removing backups older than 7 days..."
        find /backups -type f -name "backup_*.sql" -mtime +7 -delete
        echo "Cleanup completed"
      '
    profiles:
      - backup
      
volumes:
  postgres-data: